# Generated by Django 5.2.3 on 2025-06-12 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('deadline', models.DateTimeField()),
                ('description', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('done', 'Done'), ('pending', 'Pending')], default='pending', max_length=10)),
            ],
        ),
    ]
