# Generated by Django 5.2.3 on 2025-06-12 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_task_task_poeple'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='task_poeple',
            new_name='task_user',
        ),
        migrations.DeleteModel(
            name='People',
        ),
    ]
